### ISSUE TITLE
gry.lotto.pl

### ISSUE THREAD

**Issue by krystian3w** [FiltersHeroes/PolishCookieConsent#12]
https://github.com/MajkiIT/polish-ads-filter/issues/10516#issuecomment-445761493

> @lukjan32  **pisze:**
>
> ja sie dolaczam, nie mozna potwierdzic, aby wyslac kupon, nie reaguje przycisk

**Comment by krystian3w** [comment]
Ja konta nie mogę założyć, jakby je blokady rodo i cookies przerywały.

Lub nie ma numeru totalizatora, to nie ma rejestracji.

> ![obraz](https://user-images.githubusercontent.com/35370833/49746818-4823b000-fca2-11e8-8c46-0c689951dbf3.png) |
> --- |

Wisi tak już 5 minutę, trochę ratuje ich ten **HTTPS**.

**Comment by krystian3w** [comment]
Niby mi się udało ustalić że zgoda RODO zapisuje się w `local storage` - czyli jeszcze jednej funkcji byś my potrzebowali do bazy by tylko parametry podawać dla domeny.

**Comment by hawkeye116477** [comment]
No, niby
```
var showRodoModal=function(){let localst=interactive.utils.common.localStorage.localStorage;
if(localst.get("rodoConfirmation")===undefined||localst.get("rodoConfirmation")===null){setTimeout(function(){var accept=function(){localst.set("rodoConfirmation",true);
if($rootScope.isLoggedIn){showEditModal()
}else{showAgeModal()
}};
$("#modalButtonAcceptRodo").off("click").on("click",accept);
ModalService.Open("modalRodoConfirmation")
},3000)
}else{if($rootScope.isLoggedIn){showEditModal()
}else{showAgeModal()
}}};
showRodoModal()
}]);
```

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/12819
