### ISSUE TITLE
Aktualizator na Windows

### ISSUE THREAD

**Issue by krystian3w** [FiltersHeroes/PolishCookieConsent#15]
> A jeśli masz Windowsa, to masz 2 możliwości:
> 
> a)

wariant A coś nie umie się dogadać z starą wersją dodatku 1.7.1

i w efekcie mam niby aż dwa:

![image](https://user-images.githubusercontent.com/35370833/50471420-c7102c80-09b4-11e9-890b-d03d55fd8812.png) |
--- |

**Comment by krystian3w** [comment]
Chyba, że to z winy przebudowy aż ID dodatku się zmieniło.

**Comment by hawkeye116477** [comment]
Rozumiem, że jednak jest ok, tylko pewnie z innej ścieżki wczytane :smile:

**Comment by krystian3w** [comment]
Z oba z jednej, i jakby różne ID blokowały uaktualnienie już wersji 1.7.1 (nie sprawdzałem czy odblokowywała by coś z nowszych wydań), ale pewnie rozwaliłem sobie stary instalując go do:

`%UserProfile%\PolishCookieConsent_chromium`
