### ISSUE TITLE
www.dobreprogramy.pl

### ISSUE THREAD

**Issue by krystian3w** [FiltersHeroes/PolishCookieConsent#25]
W Firefox funkcja klikania w "przechodz" nie chce działać z mechanizmem ochrony prywatności.

> ![obraz](https://user-images.githubusercontent.com/35370833/60910807-13042e00-a282-11e9-87ae-ed458e7a0451.png) |
> --- |

Pewnie trzeba by po prostu innym dodatkiem blokować ciasteczka a nie mechanizmem Firefox?

**Comment by hawkeye116477** [comment]
@krystian3w Nie chce działać, bo pewnie ustawienia są zapisywane do :cookie:, więc musiałbyś zrezygnować z blokowania :cookie: na tej stronie.

**Comment by seba2282** [comment]
Odnośnie tego, Do Not Track, ochrona śledzenia tylko w kartach prywatnych i akceptacja wszystkich cookies zezwolone i na podobnych ustawieniach działa z chromowym Edge, a z Firefox już nie.

**Comment by krystian3w** [comment]
Jeszcze jest opcja że masz za dużo dodatków lub twoje milion list tak zamula przeglądarkę że nawet 1000 ms opóźnienia to za mało.

**Comment by hawkeye116477** [comment]
Nie, tu chodzi o to, że jeżeli jest blokada ciastek, to wtedy nie zadziała, to normalka.

**Comment by krystian3w** [comment]
W sumie i tak najlepsze jest, że WP śledzi klikania Enterów i po tym niby rozpoznaje użytkownika?

https://forum.dobreprogramy.pl/t/portal-komentarze-enter-2-bledy/568397/27

**Comment by seba2282** [comment]
Ublock origin z tymi samymi filtrami w obu przeglądarkach + PZC

**Comment by hawkeye116477** [comment]
Jeżeli opcja dot. :cookie: jest odznaczona, to powinno być ok. No chyba, że @seba2282 wybrał, że ma wszystkie :cookie: blokować albo dopisał coś w wyjątkach w Ciasteczka i dane stron, że ma coś blokować :smiley:

**Comment by seba2282** [comment]
Napisałem, mam zezwól na wszystkie cookies.

**Comment by krystian3w** [comment]
Znowu się zepsuło, wrócili do zielonego paska z białego wyśrodkowanego pop-upa, pewnie jakiś bug że aktywował się biały.

**Comment by krystian3w** [comment]
Konsola www mówi że element nie jest zdefiniowany:

![obraz](https://user-images.githubusercontent.com/35370833/62836483-bc648800-bc63-11e9-925f-10c76f945bb4.png) |
--- |

**Comment by seba2282** [comment]
No popatrz, nie tylko mnie denerwuje RODO/cookie na DP 😂 A tak poważnie, kiboke ma trzy opcje w I don't care about cookies (zezwalaj na wszystkie, zezwalaj na cookies potrzebne do poprawnego działania strony, blokuj wszystkie cookies). Natomiast lista sobie nadal nie radzi.

**Comment by hawkeye116477** [comment]
`Konsola www mówi że element nie jest zdefiniowany - lub że z konsoli nigdy nie zadziała (nie kliknę nawet w coś co widać):`
Najwyraźniej pomiędzy button musi być cudzysłów, bo inaczej nie przechodzi, ale pewnie to nie błąd FF, tylko tak miało być, a Chromium/Vivaldi nie sprawdza dokładnie.

**Comment by krystian3w** [comment]
Najwyżej twarda spacja w środku:

`<button class="n4k1a2v" n4k1a2v="">PRZECHODZĘ DO&nbsp;SERWISU</button>`

raczej liniowy zapis nie wyciął niewidzialnych znaków.

**Comment by hawkeye116477** [comment]
Ah, jednak w obu było nie do końca ok, tylko, że Nano mi chowało i dlatego ja nie zauważyłem.

**Comment by hawkeye116477** [comment]
@krystian3w Testuj, czy teraz lepiej. 
Jednak chyba nie chodziło o cudzysłów, tylko na FF coś nie chciała działać ta opcja z timeout, więc zrobiłem inaczej.

**Comment by seba2282** [comment]
W AG już nie działa dla głównej DP, nano też nie ogarnia. I pies pogrzebany.

**Comment by hawkeye116477** [comment]
@seba2282 Przetestuj z ostatniego commita. Pobierz repo, wejdź na `about:debugging#addons` i tam `tymczasowo wczytaj` i wskaż manifest.

**Comment by krystian3w** [comment]
W AG jak ma ruszyć to tylko z AG 3.2.2 lub nowszym (FX / Opera) nie wiem jak Edge podchodzi do skryptów dynamicznie pobieranych  - może olewają jak Chrome.

**Comment by hawkeye116477** [comment]
@krystian3w Testował, działa?

**Comment by seba2282** [comment]
AG stable 3.2.1 od pewnego czasu nie blokuje. Dlatego przetestuję za moment wyższe wersje. Jak tu będzie problem na FF, to nie wiem co dalej.

**Comment by hawkeye116477** [comment]
@krystian3w @seba2282 Nadal czekam na wasze wyniki :smile:.

**Comment by krystian3w** [comment]
Jak dla mnie poprawka może być, sprawdziłem w ViolentMonkey i kliknął. A dodatek minimalnie szybciej.

**Comment by hawkeye116477** [comment]
Już jest w AMO.

**Comment by seba2282** [comment]
Sorki, że tak późno, poprawka zadziałała. Tylko do potwierdzenia.

**Comment by krystian3w** [comment]
`Chro-Edge` może do czwartku dostanie.

**Comment by hawkeye116477** [comment]
@krystian3w A, czyli wyłożyłeś kasę dla MS i będzie w sklepie MS?

**Comment by krystian3w** [comment]
Nie trzeba niebieski pasek że pozwalasz na z chrome web store, raczej jeszcze tego MS nie zablokował.
