### ISSUE TITLE
kinopodbaranami.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishCookieConsent#27]
### Typ problemu
błąd
### Moja konfiguracja 
**System operacyjny:** Linux
**Przeglądarka internetowa:** Mozilla Firefox 68.0.2
### Dodatkowe informacje mogące mieć znaczenie
`http://kinopodbaranami.pl/repertuar.php/film.php?film_id=10332`

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
Rozszerzenie nie powoduje błędu. Chyba trzeba będzie napisać, by zgłaszający sprawdzał, czy wyłączenie coś daje, co za ludzie, zgłaszają i nawet nie sprawdzą...

**Comment by krystian3w** [comment]
`http://kinopodbaranami.pl/film.php?film_id=10332` i się naprawi 🤣.
