### ISSUE TITLE
gry.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishCookieConsent#28]
### Typ problemu
pytanie
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 75.0
### Dodatkowe informacje mogące mieć znaczenie
Loop gry - `https://www.gry.pl/gra/bubble-shooter-classic`

```
https://games.softgames.com/games/bubble-shooter-classic-HD/gamesites/844/locale/en?gp=1?gp=1&siteid=16&channelid=1&siteLocale=pl-PL&spilStorageId=93174024942
```

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Ciastko wychodzi brzydkie:

```
    oil_data:{%22opt_in%22:true%2C%22version%22:%221.2.5-RELEASE%22%2C%22localeVariantName%22:%22en%22%2C%22localeVariantVersion%22:1%2C%22customPurposes%22:[]%2C%22consentString%22:%22BOm4is5Om4is5BQABBENCl-AAAAqV7_______9______9uz_Ov_v_f__33e8__9v_l_7_-___u_-3zd4u_1vf99yfm1-7etr3tp_87ues2_Xur__79__3z3_9phP78k89r7337Ew-v-3o8A%22%2C%22configVersion%22:2}
```

`oil_data`, `games.softgames.com`, `/` `15-10-2019 17:16:34`

**Comment by krystian3w** [comment]
Nie umiem kliknąć ani upiec ciastka, może niby Local Storage użyty.

**Comment by hawkeye116477** [comment]
@krystian3w Ja tam mam tak nawet bez rozszerzenia, więc to chyba nie jest wina rozszerzenia.

**Comment by krystian3w** [comment]
Kiboke wyciął button akceptacji generykiem to zrobiłem "bugi" kiboke.

**Comment by krystian3w** [comment]
Najwyżej można na razie zostawić do ręcznej akceptacji i drugie PR z socialem i cookies.

Jedynie problem, że osoba używająca AG nie używa polskiej listy, to jej nie będzie jak przywrócić buttona nawet jak AdamWr rozgryzie jaka lista bugguje ładowanie ramki z grą i robi refresh.

**Comment by hawkeye116477** [comment]
Przejrzę to jeszcze może za parę dni i zobaczę co da się zrobić.

**Comment by krystian3w** [comment]
Zawsze można zobaczyć czy Kiboke wymyśli klikacz, a u nas uznać to za weryfikator wiekowy, niby wymagają by w kulki grał 16 latek 🤣.

**Comment by hawkeye116477** [comment]
@krystian3w Kiboke to w cale zepsuł, strona odświeża się chyba z 50 razy i nie może przestać.

**Comment by krystian3w** [comment]
A czyli dodatek miesza a nie filtry w AG, a to dobre... 😣.

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/40482

**Comment by hawkeye116477** [comment]
No to skoro wymagają odpowiedniego wieku, to może jednak to zostawimy.
Choć z drugiej strony, to dziwne wymagania mają, 16-latkowie raczej w innego typu gry grają.

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/21665 https://github.com/MajkiIT/polish-ads-filter/issues/15134
