### ISSUE TITLE
[SSL/TLS] naszemiasto.pl

### ISSUE THREAD

**Issue by FadeMind** [FiltersHeroes/PolishCookieConsent#47]
Dowolna subdomena z NaszeMiasto.pl 

Pojawia się błąd o treści `ERR_TOO_MANY_REDIRECTS`, gdy rozszerzenie Polska Ciasteczkowa Zgoda jest włączone.

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 X64
Browser:                               | Google Chrome Stable X64
**AdGuard Browser Assistant Beta** | installed and enabled
AdGuard version:                       | **7.4 NIGHTLY** 
Protection Mode:| **WFP Driver**
Stealth Mode:       | disabled

| **=== FILTERS ENABLED ===**
|---|
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| I don't care about cookies
| EasyList Cookie List
| **SECTION :: Security**
| Malware Domains
| Spam404
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty 
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

```
Edytowano przed moderatora
Powód edycji: moderator poprawił błędy ortograficzne.
```

**Comment by hawkeye116477** [comment]
Raczej wątpię, że PCZ powoduje problem. Jeżeli chodzi o przekierowania, to są jedynie 2 takie reguły do stron `powiatkamienski.pl` i `f1racing.pl`. Nic nie ma odnośnie naszego miasta. 

Sprawdziłem na `https://warszawa.naszemiasto.pl` i wszystko jest ok.

Może @FadeMind sam coś dopisał i zapomniał.

**Comment by krystian3w** [comment]
Ja też mam pętle:

- nic raczej nie dopisał, 
- dezaktywacja dodatku na `subdomenie` nic nie daje,
- wyłączenie dodatku może daje efekt placebo.

**Comment by krystian3w** [comment]
Pętla może robi się od tego że główną stronę da się otworzyć nieszyfrowaną a subdomeny mają już TLS.
