### ISSUE TITLE
kontrowersje.net

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishCookieConsent#51]
### Typ problemu
błąd
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox 76.01
### Dodatkowe informacje mogące mieć znaczenie
dodatek zgoda ciasteczkowa nie działa na stronie kontrowersje.net

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
Podobnie jak https://github.com/PolishFiltersTeam/PolishCookieConsent/issues/53#issuecomment-633053848, dodatkowo lista filtrów **I don't care about cookies** jest wymagana.
