### ISSUE TITLE
wpolityce.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishCookieConsent#54]
### Typ problemu
błąd
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox 76.01
### Dodatkowe informacje mogące mieć znaczenie
dodatek do firefoxa "zgoda ciasteczkowa" nie działa na stronie wpolityce.pl

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
To nie błąd, rozszerzenie to jest jedynie uzupełnieniem listy **Polskie Filtry Rodo-Ciasteczkowe** (nie dodajemy to co w uBO już jest ukrywane).
