### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/PolishCookieConsent#58]
Coś pozmieniali 
![2020-08-13 12 55 26 www dobreprogramy pl 1d0fcebd427b](https://user-images.githubusercontent.com/36385327/90126642-45753a00-dd64-11ea-9c81-332698622256.png)

**Comment by hawkeye116477** [comment]
Dziwna sprawa, jak z konsoli wpisuję `document.evaluate("//" + "button" + "[contains(text(), " + '"' + "PRZECHODZ" + '"' + ")]", document, null, XPathResult.ANY_TYPE, null).iterateNext().click();|`, to od razu wywala coś z ich skryptu `Uncaught TypeError: Cannot read property 'setPurposesAllowed' of undefined`. Co oni teraz zaczęli bawić się w wykrywanie programistycznego klikania?

**Comment by krystian3w** [comment]
Teraz nie używają zieleni i doczepili logo WP, ciekawe kiedy zmienią nazwę buttona.
