### ISSUE TITLE
play24.pl - The requested URL was rejected

### ISSUE THREAD

**Issue by FadeMind** [FiltersHeroes/PolishCookieConsent#61]
## The requested URL was rejected. Please consult with your administrator. Your support ID is 

Rozszerzenie coś robi w tle co powoduje problem z przekierowaniem ze strony logowania SSO do portalu. 

Strona logowania:
`https://logowanie.play.pl/p4-idp2/SSOrequest.do?action=sso`
powinna przekierować do:

`https://24.play.pl/Play24/Welcome` przekierowuje do strony błędu `https://logowanie.play.pl/opensso/logowanie` z treścią:
```
 The requested URL was rejected. Please consult with your administrator. Your support ID is XXXXXXXXXX
```
gdzie XX to losowy numer. 

![20201014-1602704119-001](https://user-images.githubusercontent.com/9846948/96036758-36466180-0e65-11eb-8000-40c8568e84ce.png)
![20201014-1602704093-001](https://user-images.githubusercontent.com/9846948/96036762-37778e80-0e65-11eb-9252-ae0116bc2bdb.png)
Jak wyłączyłem dodatek to natychmiast przekierowało mnie na właściwą stronę po zalogowaniu.

**Comment by hawkeye116477** [comment]
Jaka przeglądarka?

**Comment by FadeMind** [comment]
Chrome

**Comment by hawkeye116477** [comment]
Ok, teraz złapałem, ale na Waterfoksie, z tym, że strona zadziałała dopiero po wyłączeniu i włączeniu uBO.

W tle jedyny skrypt jaki jest to aktualizacje bazy. Żadnej reguły w PCC na tą stronę nie ma, więc też nie chce mi się wierzyć jakby coś tam miało powodować problem.

**Comment by FadeMind** [comment]
U mnie w tle działa Adguard dla Windowsa z dodatkiem https://chrome.google.com/webstore/detail/adguard-browser-assistant/fbohpolgemkbfphodcfgnpjcmedcjhpn

**Comment by hawkeye116477** [comment]
Sprawdziłem ponownie, znowu jest błąd, ale wyłączyłem oba i nadal mam. Tak więc obstawiam, że to jednak problem po stronie serwera.
