### ISSUE TITLE
Zgoda ciasteczkowa - Adguard

### ISSUE THREAD

**Issue by mlkf2014** [FiltersHeroes/PolishCookieConsent#70]
Zaczynam na Gicie i proszę wszystkich o wyrozumiałość. Moje pytanie:
Mam na androidzie Agduarda, czy rozszerzenie PZC można zaimportować do rozszerzeń agduarda czy też może to działać jako lista filtrów?

**Comment by hawkeye116477** [comment]
Podwójne nie.

Teoretycznie w AG może i dałoby się dodać podobne reguły jak w PCZ, bo niby tam każdy kod można dodać, ale żeby lista działała trzeba być ważną szychą w firmie AG. Dla zwykłych zarządców list są ograniczenia.

**Comment by mlkf2014** [comment]
Dzięki wielkie za odpowiedź.

**Comment by hawkeye116477** [comment]
Na Androidzie masz do wyboru przeglądarki Kiwi oraz Yandex i do nich możesz doinstalować PCZ z Chrome Web Store.
Ewentualnie może [Iceraven](https://github.com/fork-maintainers/iceraven-browser) albo Firefox, ale dawno nie sprawdzałem, czy tam działa.

**Comment by mlkf2014** [comment]
Rozumiem, ale ja używam duck'a a tam nic się nie da zrobić, więc myślałem że może w adguardz spróbuje. Dzięki wielkie.

**Comment by krystian3w** [comment]
Kiedyś był jako `.user.js` ale ten kod już nie jest dostępny raczej online i jest porzucony jak znajdziesz ostatnią wersje.
